// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PopupReach - Launch Local Promos That Pop Up at the Right Time',
  description: 'PopupReach helps local businesses deliver real-time promotions to nearby customers and gives shoppers instant access to deals they care about.',
  keywords: ['local business', 'promotions', 'deals', 'location-based marketing', 'popup deals'],
  authors: [{ name: 'PopupReach' }],
  creator: 'PopupReach',
  publisher: 'PopupReach',
  openGraph: {
    title: 'PopupReach - Launch Local Promos That Pop Up at the Right Time',
    description: 'Real-time promotions for local businesses and instant deals for nearby shoppers.',
    url: 'https://popupreach.com',
    siteName: 'PopupReach',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'PopupReach - Local Promotion Platform',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PopupReach - Launch Local Promos That Pop Up at the Right Time',
    description: 'Real-time promotions for local businesses and instant deals for nearby shoppers.',
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}